package model_test

import (
	"github.com/codestand/build/model"
	"testing"
)

func TestAll(t *testing.T) {
	model.Open()
	defer model.Close()

	builds := model.All()
	for _, b := range builds {
		if b.Id == 10000 {
			return
		}
	}

	t.Fatal("id=10000 should be found, and it can be generated by script/activerecord/seed.rb")
}
