package model_test

import (
	"github.com/codestand/build/model"
	"testing"
)

func TestAllModels(t *testing.T) {
	model.Open()
	defer model.Close()

	builds := model.All()
	for _, b := range builds {
		if b.Id == 10000 {
			return
		}
	}

	t.Fatal("id=10000 should be found, and it can be generated by script/activerecord/seed.rb")
}

func TestModelFound(t *testing.T) {
	model.Open()
	defer model.Close()

	b := model.Build{Id: 10000}
	model.Find(&b)
	if b.Id != 10000 {
		t.Fatal("id=10000 should be found, and it can be generated by script/activerecord/seed.rb")
	}
}

func TestModelNotFound(t *testing.T) {
	model.Open()
	defer model.Close()

	b := model.Build{Id: 99999}
	if !model.Find(&b).RecordNotFound() {
		t.Fatal("id=99999 should not be found")
	}
}
